[package]
name = "tint"
version = "0.1.0"
edition = "2024"

[features]
serde = ["dep:serde"]
std = ["serde?/std"]

[dependencies]
serde = { version = "1.0", optional = true, default-features = false, features = [
	"derive",
] }
